### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by langelesl** [claydergc/loam_velodyne_kitti_ros#2]
Hi.

I tried to compile and install your repo in my workspace but failed. 

![Screenshot from 2019-03-11 21-59-34](https://user-images.githubusercontent.com/45672268/54157829-63d95680-4449-11e9-8228-4f8692918845.png)

Could you please give me any tips about your version of compiler and pcl? I am using g++ 5.4.0 and pcl 1.9.0. 

Thanks.

**Comment by claydergc** [comment]
Sorry for the late responde. I used g++ 7.3.0 and pcl 1.8. Try replacing isnan() with std::isnan() and pcl_isfinite() with std::isfinite(). Hope it works

**Comment by langelesl** [comment]
Thanks Clayder. The make problem is solved.
